language: julia
julia:
    - 0.3
    - release
    - nightly
notifications:
    email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("MatpowerCases"); Pkg.test("MatpowerCases"; coverage=true)'
after_success:
- julia -e 'cd(Pkg.dir("MatpowerCases")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
