language: julia
julia:
    - release
    - nightly
script:
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.build("$name")'
    - if [ $JULIAVERSION = "julianightlies" ]; then julia test/runtests.jl; fi
    - if [ $JULIAVERSION = "juliareleases" ]; then julia --code-coverage test/runtests.jl; fi
after_success:
- julia -e 'cd(Pkg.dir("MatpowerCases")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
